### ISSUE TITLE
Levenberg-Mardquat Running exceptionally slow unless verbose is enabled

### ISSUE THREAD

**Issue by pablovela5620** [google/jaxopt#277]
Levenberg-Mardquat optimizer runs exceptionally slow (~30 seconds for 30 iterations) until I turn on `verbose==True` (~1 second for 30 iterations. Any idea what may be going on? enabling JIT seems to have no impact. Was hoping to use this for a real-time system but even at 1 second things are way too slow.

**Comment by mblondel** [comment]
Verbose mode disables jit compilation so this suggests that jit compilation is slow, either in our Levenberg-Mardquat implementation itself or in your `residual_fun`. Do you do anything fancy in your `residual_fun`? Is it slow to compile with `jax.jit(residual_fun)`? CC @amir-saadat

**Comment by pablovela5620** [comment]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/25287427/181079161-e3a53b57-ef25-486c-8cad-d35432e21c3a.png">

doesn't seem like it has to do with the residual function I have, though it looks like there is no real increase when using jit on my custom residual

**Comment by mblondel** [comment]
Does the compilation step `jax.jit(residuals_3d)` itself take time?

**Comment by pablovela5620** [comment]
doesn't seem to be the case, since both blocks take 5.9 seconds and the compilation is included in the block where I test the jit_residual

**Comment by pablovela5620** [comment]
Another thing that makes me think it may have to do with the LM implementation is that I've used this residual function/loss function with the JAX [example optimizer library](https://jax.readthedocs.io/en/latest/jax.example_libraries.optimizers.html) (specifically the adam implementation) and don't have this problem. It runs in ms rather than seconds when using JIT

**Comment by mblondel** [comment]
Thanks for checking!

Something seems to make `lax.while_loop` slow. My guess is that it may be the nested functions [here](https://github.com/google/jaxopt/blob/main/jaxopt/_src/levenberg_marquardt.py#L185).

**Comment by pablovela5620** [comment]
I rewrote a quick and dirty version just to check
```python
class CustomLM():
    def __init__(self, function, iters=30, damping_factor=1e-6) -> None:
        self.iters = iters
        self.damping_factor = damping_factor
        self.increase_factor = 2.0
        self.res_func = function
        self.found = False
        self.tol = 1e-6 # tolerance for convergence
        self.gtol = 1e-3 # gradient inf norm tolerance

    def init_state(self, params, joints_pred_3d):
        residual = self.res_func(params, joints_pred_3d)
        loss = 0.5 * npj.dot(residual, residual)
        jacobian = jax.jacobian(self.res_func)(params, joints_pred_3d)
        gradient = npj.dot(jacobian.T, residual)
        jtj = npj.dot(jacobian.T, jacobian)
        jtj_diag = npj.diag(jtj)

        self.damping_factor = self.damping_factor * npj.max(jtj_diag)
        return gradient, jtj, residual, loss

    def run(self, init_params, joints_pred_3d):
        params = init_params
        iter_num = 0
        gradient, jtj, residual, loss = self.init_state(params, joints_pred_3d)

        while iter_num < self.iters and not self.found:
            error = npj.linalg.norm(gradient)
            self.found = error < self.tol

            iter_num += 1
            g = jtj + self.damping_factor * npj.eye(jtj.shape[0])
            delta_params = npj.linalg.inv(g) @ gradient
            # follow lm jaxopt
            delta_params = -delta_params
            params_new = params + delta_params
            residual_next = self.res_func(params_new, joints_pred_3d)
            gain_ratio_denom = 0.5 * delta_params.T @ (self.damping_factor * delta_params - gradient)
            loss_next = 0.5 * npj.dot(residual_next, residual_next)

            gain_ratio = (loss - loss_next) / gain_ratio_denom

            if gain_ratio > 0:
                params = params_new
                residual = residual_next
                loss = loss_next
                jacobian = jax.jacobian(self.res_func)(params, joints_pred_3d)
                gradient = npj.dot(jacobian.T, residual)
                jtj = npj.dot(jacobian.T, jacobian)

                self.damping_factor = self.damping_factor * jax.lax.max(1 / 3, 1 -
                                                    (2 * gain_ratio - 1)**3)
                self.increase_factor = 2.0

            else:
                self.damping_factor *= self.increase_factor
                self.increase_factor *= 2

        return params

updated_params = CustomLM(residuals_3d).run(init_params, xyz_gt)
%timeit CustomLM(residuals_3d).run(init_params, xyz_gt)
```

<img width="542" alt="image" src="https://user-images.githubusercontent.com/25287427/181112059-28f2e110-0fee-4b54-bd3d-b8770000027f.png">

compared to the Jaxopt implementation
<img width="992" alt="image" src="https://user-images.githubusercontent.com/25287427/181112571-891f66e0-9e03-4178-9bac-52a1676ab83a.png">

**Comment by amir-saadat** [comment]
Thanks @pablovela5620 for the info. Did you try jitting your custom version and timing it? I am curious if the jitted version shows considerable timing difference.

**Comment by amir-saadat** [comment]
I couldn't reproduce the issue regarding with verbose=True/False with the unit test. In particular I tested `test_rosenbrock_x64` and `test_double_exponential_fit_x64` in the unit tests (https://github.com/google/jaxopt/blob/main/tests/levenberg_marquardt_test.py) and with verbose=False I get around 1s and verbose=True I get 7s and 17s respectively.

**Comment by pablovela5620** [comment]
@amir-saadat Unfortunately, the custom version I built can't be jitted due to using control flow (I'm in the process of converting python control flow to lax). I'm not fully sure as to how jit/lax function as I'm fairly new to Jax. Once I have a version that uses lax control flow will update. One issue I'm facing is that I'm not fully sure how I would go about using jit on class methods, I seem to get the following error

`TypeError: Argument '<__main__.CustomLM23D object at 0x7fe90429e460>' of type <class '__main__.CustomLM23D'> is not a valid JAX type.`

when I do this
```python
@jit
def run(self, init_params, cams, joints_pred_2d, z_pred_depth):
    params = init_params
    iter_num = 0
    gradient, jtj, residual, loss = self.init_state(params, cams, joints_pred_2d, z_pred_depth)

    while iter_num < self.iters and not self.found:
        error = npj.linalg.norm(gradient)
        self.found = error < self.tol

        iter_num += 1
        g = jtj + self.damping_factor * npj.eye(jtj.shape[0])
        delta_params = npj.linalg.inv(g) @ gradient
        # follow lm jaxopt
        delta_params = -delta_params
        params_new = params + delta_params
        residual_next = self.res_func(params_new, cams, joints_pred_2d, z_pred_depth)
        gain_ratio_denom = 0.5 * delta_params.T @ (self.damping_factor * delta_params - gradient)
        loss_next = 0.5 * npj.dot(residual_next, residual_next)

        gain_ratio = (loss - loss_next) / gain_ratio_denom

        if gain_ratio > 0:
            params = params_new
            residual = residual_next
            loss = loss_next
            jacobian = jax.jacobian(self.res_func)(params, cams, joints_pred_2d, z_pred_depth)
            gradient = npj.dot(jacobian.T, residual)
            jtj = npj.dot(jacobian.T, jacobian)

            self.damping_factor = self.damping_factor * jax.lax.max(1 / 3, 1 -
                                                (2 * gain_ratio - 1)**3)
            self.increase_factor = 2.0

        else:
            self.damping_factor *= self.increase_factor
            self.increase_factor *= 2

    return params
```

**Comment by amir-saadat** [comment]
yes, jitting this exact version won't work, cause `iter_num ` and `gain_ratio ` are traced and you would need to use lax.cond and jnp.where.

**Comment by pablovela5620** [comment]
I'll try to generate a colab notebook with my code to see if I can reproduce it on a different machine. Appreciate the help

**Comment by amir-saadat** [comment]
If you could share more information about your residual function, it would great. We can then test any potential improvement.
BTW, how have you been comparing your LM results and timing with optax? I am asking cause as you know, LM (as a nonlinear least-squares method) would be very different than something like GD.

**Comment by pablovela5620** [comment]
Yep will do, I'll post a notebook soon as having a fast version of levenberg mardquat (without having to use ceres) would be very helpful. 

I'm basically trying to reimplement something very similar to the [MegaTrack](https://scontent-dfw5-1.xx.fbcdn.net/v/t39.8562-6/10000000_235193588494349_3727758571190956731_n.pdf?_nc_cat=101&ccb=1-7&_nc_sid=ad8a9d&_nc_ohc=djH-LaAODJsAX--K_Yl&_nc_ht=scontent-dfw5-1.xx&oh=00_AT8C-PYDUj0WqI4t3mJoAseg2Mn63U3sI_MSurpBPv7bTg&oe=62E545CA) paper. Specifically this

<img width="858" alt="image" src="https://user-images.githubusercontent.com/25287427/181120558-657f06a3-37e1-4cdd-9d1a-7a7ec9543ac1.png">
<img width="847" alt="image" src="https://user-images.githubusercontent.com/25287427/181120615-4269acf9-fe1a-441c-a54a-03f38d413249.png">

**Comment by pablovela5620** [comment]
[COLAB LINK](https://colab.research.google.com/drive/1EBKk_ArxzR5BnHALsVqbmDIG0ciHKG9d?usp=sharing)
Here's a link to a stripped-down version of my code. You can see a few things here

1.  ORIGINAL LM not using JIT  169 ms ± 3.7 ms per loop
2. ORIGINAL LM using JIT  7.64 s ± 33.4 ms per loop
3. CUSTOM LM not using JIT 3.89 ms ± 28.1 µs per loop

**Comment by pablovela5620** [comment]
I updated my implementation to use lax.while_loop, and found that this version is about a factor of 10 faster (~40 ms)
``` python
class CustomLevenBergMarquardt:

  def __init__(self, residual_fun, maxiter=30) -> None:
    self.residual_fun = residual_fun
    self.jacobian_fun = jax.jacobian(residual_fun)
    self.maxiter = maxiter
    self.damping_parameter = 1e-6
    self.tol = 1e-6
    self.verbose = False

  def _cond_fun(self, inputs):
    _, state = inputs[0]
    if self.verbose:
      print("error:", state.error)
    return state.error > self.tol

  def _body_fun(self, inputs):
    (params, state), (args, kwargs) = inputs
    return self.update(params, state, *args, **kwargs), (args, kwargs)

  def init_state(self, init_params, *args, **kwargs):
    # Compute actual values of state variables at init_param
    residual = self.residual_fun(init_params, *args, **kwargs)
    jacobian = self.jacobian_fun(init_params, *args, **kwargs)
    gradient = np.dot(jacobian.T, residual)
    jtj = np.dot(jacobian.T, jacobian)
    # found = jnp.linalg.norm(grad, jnp.inf) <= gtol
    jtj_diag = np.diag(jtj)
    damping_factor = self.damping_parameter * np.max(jtj_diag)
    delta_params = np.zeros_like(init_params)

    return LevenbergMarquardtState(
        iter_num=np.asarray(0),
        damping_factor=damping_factor,
        increase_factor=2,
        error=np.linalg.norm(gradient),
        residual=residual,
        loss=0.5 * np.dot(residual, residual),
        delta=delta_params,
        gradient=gradient)

  def gain_ratio_test_true(
    self,
    params,
    damping_factor,
    gain_ratio,
    increase_factor,
    residual,
    gradient,
    updated_params,
    *args, **kwargs):

    params = updated_params

    residual = self.residual_fun(params, *args, **kwargs)

    # Calculate gradient based on Eq. 6.6 of "Introduction to optimization
    # and data fitting" g=JT * r, where J is jacobian and r is residual.
    jacobian = self.jacobian_fun(params, *args, **kwargs)
    gradient = np.dot(jacobian.T, residual)

    damping_factor = damping_factor * jax.lax.max(1 / 3, 1 -
                                                  (2 * gain_ratio - 1)**3)
    increase_factor = 2

    return params, damping_factor, increase_factor, gradient, residual

  def gain_ratio_test_false(
    self,
    params,
    damping_factor,
    gain_ratio,
    increase_factor,
    residual,
    gradient,
    updated_params,
    *args, **kwargs
    ):
    damping_factor = damping_factor * increase_factor
    increase_factor = 2 * increase_factor
    return params, damping_factor, increase_factor, gradient, residual
        
  def update(self, params, state, *args, **kwargs):
    '''
    update the state of the optimizer for levenberg marquardt
    '''
    # Current value of the loss function F=0.5*||f||^2.
    loss_curr = state.loss

    # solve for delta_params
    jtj = self.jacobian_fun(params, *args, **kwargs).T @ self.jacobian_fun(params, *args, **kwargs)
    g = jtj + state.damping_factor * np.eye(jtj.shape[0])
    delta_params = np.linalg.inv(g) @ state.gradient
    delta_params = -delta_params

    # calculate gain_ratio
    updated_params = params + delta_params

    residual_next = self.residual_fun(updated_params, *args, **kwargs)
    # Calculate denominator of the gain ratio based on Eq. 6.16, "Introduction
    # to optimization and data fitting", L(0)-L(hlm)=0.5*hlm^T*(mu*hlm-g).
    gain_ratio_denom = 0.5 * delta_params.T @ (state.damping_factor * delta_params - state.gradient)

    # Current value of loss function F=0.5*||f||^2.
    loss_next = 0.5 * np.dot(residual_next, residual_next)

    gain_ratio = (loss_curr - loss_next) / gain_ratio_denom
    
    gain_ratio_test_is_met = gain_ratio > 0

    true_ret = self.gain_ratio_test_true(params, state.damping_factor, gain_ratio, state.increase_factor, state.residual, state.gradient, updated_params, *args, **kwargs)
    false_ret = self.gain_ratio_test_true(params, state.damping_factor, gain_ratio, state.increase_factor, state.residual, state.gradient, updated_params, *args, **kwargs)

    gain_ratio_test_is_met_ret = jax.tree_map(
        lambda x: gain_ratio_test_is_met * x, true_ret)

    gain_ratio_test_not_met_ret = jax.tree_map(
        lambda x: (1.0 - gain_ratio_test_is_met) * x,
        false_ret)

    params, damping_factor, increase_factor, gradient, residual = jax.tree_map(
        lambda x, y: x + y, gain_ratio_test_is_met_ret,
        gain_ratio_test_not_met_ret)

    state = LevenbergMarquardtState(
        iter_num=state.iter_num + 1,
        damping_factor=damping_factor,
        increase_factor=increase_factor,
        error=np.linalg.norm(gradient),
        residual=residual,
        loss=0.5 * np.dot(residual, residual),
        delta=delta_params,
        gradient=gradient)
    
    return OptStep(params, state)
    
  def __call__(
    self,
    init_params,
    *args,
    **kwargs
    )->OptStep:
    # 1. initialize solver state
    state = self.init_state(init_params, *args, **kwargs)
    # zero_step = OptStep(init_params, state)
    # 2. perform first optimization step
    opt_step = self.update(init_params, state, *args, **kwargs)

    # needed for lax while loop
    init_val = (opt_step, (args, kwargs))

    many_step = _while_loop_lax(
      cond_fun=self._cond_fun,
      body_fun=self._body_fun,
      init_val=init_val,
      maxiter=self.maxiter - 1)

    return many_step
```

at the recommendation of @mblondel I extracted out the sub functions. I didn't test with them nested, but seems like that may have helped? Theres some overhead thats still making it slower than just using naitve python while loops, but I'm also using a super simple residual function. 

I also updated the [COLAB](https://colab.research.google.com/drive/1EBKk_ArxzR5BnHALsVqbmDIG0ciHKG9d?usp=sharing) notebook to include this new implementation. Will continue to test with more complicated residual functions to see if the lax while loop helps when paired with JIT

**Comment by amir-saadat** [comment]
thanks @pablovela5620 for testing. There are multiple potentially factors here: 
Recently, I've been testing the timing for LM, and I had noticed that direct calculation of JT.J is more efficient than using jtj_op (in the current version of jaxopt) for smaller problems. There is an update coming up where the user can provide `materialize_jac` where terms like JT.J are explicitly calculated rather than using jax jvp and vjp.
The other part that you have is nested function as @mblondel suggested. I've pushed a branch (https://github.com/amir-saadat/jaxopt/tree/improve-lm-timing). Would it be possible to import this branch in your colab and test how much only this avoiding nested functions is helping?

**Comment by pablovela5620** [comment]
Unfortunately, it looks like the nested update functions aren't what was causing the slowdown. (I updated the colab to test it).
<img width="802" alt="image" src="https://user-images.githubusercontent.com/25287427/181608822-7a37afcc-8114-4637-9673-b4d47112c8fb.png">
I'm still getting around 8 seconds v.s. the ~20 ms that I get when using the stripped-down implementation I made (that I posted above).

<img width="541" alt="image" src="https://user-images.githubusercontent.com/25287427/181610494-44218c61-23d8-464a-8ff5-8461f11c4610.png">
 
I'm not sure what may be causing it since I haven't done any significant profiling to the implementation included in the JaxOpt package

**Comment by amir-saadat** [comment]
so it is not actually surprising for me, I wasn't expecting it will have a great effect.
I have added the `materialize_jac` option in the same branch. could you please test your runs by passing `materialize_jac=True`?

**Comment by pablovela5620** [comment]
Okay looks like that did help! 
<img width="998" alt="image" src="https://user-images.githubusercontent.com/25287427/181636337-1923fcad-9a19-44ce-86c1-bf6ca24ba9d3.png">
But theres still the extremely weird bit that enabling JIT slows things a few orders of magnitude down. Along with this, its still about 4x slower than the custom version. I'm not sure whats causing the slow down when using JIT to take multiple seconds to optimize

NO JIT - 80 ms per loop
JIT - 3450 ms per loop
CUSTOM JIT 20 ms per loop

**Comment by mblondel** [comment]
I agree: the `materialize_jac=True` option is good but it's orthogonal. `verbose=True` (which makes JAXopt switch from `lax.while_loop` to Python loops) shouldn't be an order of magnitude faster... Looks like XLA is producing very bad code.

**Comment by amir-saadat** [comment]
I looked at your colab more closely and think that the timings need to be performed more carefully. In particular, you need to make sure that you are not averaging the compilation time with running time when using `jaxopt`'s LM. I rearranged some of your timing code and used `time.process_time` to extract the CPU time. What I see is that, the compilation of both approaches (jaxopt original implementation and the custom version) are similar. Jaxopt's runtime is actually being returned much less if you make sure you are not including the compilation time. Let me know if you can reproduce this on your end.

![image](https://user-images.githubusercontent.com/19432765/182246528-25dae957-9492-4db5-88a3-8d640fef4d0a.png)

![image](https://user-images.githubusercontent.com/19432765/182263433-401d4bb9-abb7-400d-ba0e-354aeec8d1c8.png)

**Comment by pablovela5620** [comment]
I managed to reproduce it, I actually kept the complication within the same block, but what turned out to be the issue was this 
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/25287427/182693310-96896d22-ad2e-48fd-af35-00ef26787b49.png">


being fairly new to jax/jaxopt. I did not realize that setting `jit=True` was not enough, and needed to use the jit again on the `optimizer.run` function in order to get the benefits 🤦. I was just doing
```python
LevenbergMarquardt(..., jit=True)
```

I had gotten around it on my end by calling jit directly on my custom optimizer since I used __call__ instead of .run() and didn't notice the mistake

 I apologize for the confusion, this was very instructive and both you @amir-saadat and @mblondel were super helpful in me finding a solution. It may help others to potentially have an FAQ in the documentation to explain how to correctly get JIT working with jaxopt.

Thank you again!
